flags:
  owl:
    library-only: false
    dev: false
packages:
- '.'
- '../owl-auth'
- '../yesod-pnotify'
extra-deps:
- crypto-pubkey-openssh-0.2.7
- utility-ht-0.0.11
- yesod-auth-hashdb-1.4.2.2
resolver: lts-3.4
