Emailaddress: Email address
AccountID: Account ID
CurrentPassword: Current Password
NewPassword: New Password
ConfirmPassword: Confirm

Owl: Owl
Home: Home
Help: Help
AdminTool: Admin Tool
Settings: Settings
Logout: Logout

ForgetPassword: Forget Password?
Usage: Usage

SendReminderMail: Send reminder mail

NOTE: NOTE

Account: Account
Password: Password
Email: Email
Profile: Profile

Update: Update
Edit: Edit
ChangeAvatar: Change avatar
UploadPhotos: Upload photos
EditProfile: Edit Profile
EditComment: Edit Comment

ChoiceAsAvatar: Choice as avatar
FirePhoto: Fire photo

Browse: Browse
Upload: Upload

FamilyName: Family Name
GivenName: Given Name

Close: Close
