OwlSystem: This is Owl Authentication system.
ThisIsOwl: This is Owl.
LoginFromHere: Login from here.

Emailaddress: Email address
AccountID: Account ID
CurrentPassword: Current Password
NewPassword: New Password
ConfirmPassword: Confirm
ConfirmNewPassword: Confirm

Owl: Owl
Home: Home
Help: Help
AdminTool: Admin Tool
Settings: Settings
Logout: Logout

ForgetPassword: Forget Password?
IfYouLostPassword: If you lost your password, reset password by using email reminder.
ReceiveResetMail: You can login to the Owl at one time.
Usage: Usage
DescrptForUsage: (No description)

SendReminderMail: Send reminder mail
FailSentReminderMail: Fail to send reminder mail

SendVerifyMail: Send verify mail
FailSentVerifyMail: Fail to send verify mail

NOTE: NOTE

Account: Account
Password: Password
Email: Email
Verkey: Verify Key
Verstatus: Verify Status
Profile: Profile

Update: Update
Edit: Edit
EditProfile: Edit Profile
EditComment: Edit Comment

UploadFilePath: File path
Browse: Browse
Upload: Upload

FamilyName: Family Name
GivenName: Given Name
Role: Role

Add: Add
Close: Close

AdministratorsToolbox: Administrator's Toolbox
MaintUser: Maint user
ImportUser: Import user
MaintClient: Maint client

AddNewFace: Add new face
CreateUser: Create
CreateNewFace: Created new face
FailToCreateUser: Fail to create new user
EditUser: Edit
KillUser: Kill
UserKilled: User killed.
NoteToKillUser: Be carefull to kill user. Couldn't revert the account.

Warning: Warning!
Danger: Danger!
Important: Important!

AddNewClient: Add new client
ClientID: Client ID
ClientName: Client Name
ClientSecret: Client Secret
EditClient: Client
Fire: Fire
YouUnauthorizedClient: You are Unauthorized client.

PasswordUpdated: Password updated.
PasswordsUnmatch: Passwords don't match.
FailToUpdatePassword: Fail to updated password.
InvalidCurrentPassword: Invalid current password.

Verify: Verify
VerifyKey: Verify key
VerifyYourEmail: Please verify your email address by using this verify key.
YourVerifyingEmail: Your verifying email address
NotSetAnyEmail: You've not set any verifying email address.
SuccessVerifyEmail: success to verify your email address.
FailVerifyEmail: fail to verify your email address.
SentVerifyMail: Send verify mail

UpdateProfile: Update profile.Wait about 10 min to reflect the other systems.
FailUpdateProfile: Fail to update profile

NoEmailAddress: No email address
Fullname: Name

UpdateEmailaddress: Update email address.Wait about 10 min to reflect the other systems.
FailToUpdateEmail: Fail to update email address

SuccessImportUsers: Success import users
FailToImportUsers: Fail to import users

AboutCSVFormat: Use UTF-8 and require header on first line. Columns's format is below.
AboutAccountIdColumn: User Account ID
AboutPasswordColumn: User default password
AboutEmailColumn: User's email address
AboutFamilyNameColumn: User's family name
AboutGivenNameColumn: User's given name

ThisMailaddressIs: This mail address is
Post4ThisMailaddressIs: now.

UnverifiedEmailaddress: Unverified email address.
TheAccountPasswordInvalid: The account/password are invalid.

NoteToChangeOthersPassword: Be carefull to change user's password.
NoteToChangeOthersEmail: Be carefull to change user's email address.

ConfigUserSetting: Config user settings
DescriptForConfigSetting: No item to configure on this version.

VerifyYourEmailAddress: Verify your email address
ConfirmEmailAddress: Please confirm your email address by clicking on the link below.
Thankyou: Thank you

SendPasswordReset: Send password reset mail.
CannotFindAccount: Can not find the account.
CannotSendPasswordReset: Can not send password reset mail.
ResetYourPassword: Reset your password.
LoginByOnetimepass: Please login the one time password by clicking on the link below.
IfYouDontRequestOnetimepassMail: Ignore this mail, if you don't request to create an onetime password.
OnetimePassword: Onetime Password
LoginByOnetimePassword: Login by onetime password
SuccessLoginByOnetimePassword: Success to login by the onetime password.
FailLoginByOnetimePassword: Fail to login by the onetime password.
OnetimeLoginURL: Login URL(onetime password)
OnetimeLogin: Onetime password Login

ResetPasswordOnOnetimeLogin: Reset password on onetime login
ResetPassword: Reset password
