Emailaddress: Email address
AccountID: Account ID
CurrentPassword: Current Password
NewPassword: New Password
ConfirmPassword: Confirm

Owl: Owl
Home: Home
Help: Help
AdminTool: Admin Tool
Settings: Settings
Logout: Logout

ForgetPassword: Forget Password?
Usage: Usage

SendReminderMail: Send reminder mail

NOTE: NOTE

Account: Account
Password: Password
Email: Email
Profile: Profile

Update: Update
Edit: Edit
ChangeAvatar: Change avatar
UploadPhotos: Upload photos
EditProfile: Edit Profile
EditComment: Edit Comment

ChoiceAsAvatar: Choice as avatar
FirePhoto: Fire photo

Browse: Browse
Upload: Upload

FamilyName: Family Name
GivenName: Given Name

Close: Close

AdministratorsToolbox: Administrator's Toolbox
MaintUser: Maint user
ImportUser: Import user
MaintClient: Maint client

AddNewFace: Add new face
EditUser: Edit
KillUser: Kill

Warning: Warning!
Danger: Danger!
Important: Important!

AddNewClient: Add new client
ClientID: Client ID
ClientName: Client Name
ClientSecret: Client Secret
EditClient: Edit Client
Fire: Fire

PhotoPath: Photo Path

PasswordUpdated: password updated.
FailToUpdatePassword: fail to updated password.

Verify: Verify
VerifyKey: Verify key
VerifyYourEmail: Please verify your email address by using this verify key.
YourVerifyingEmail: Your verifying email address
NotSetAnyEmail: You've not set any verifying email address.
SuccessVerifyEmail: success to verify your email address.
FailVerifyEmail: fail to verify your email address.
SendVerifyMail: Send verify mail
