Emailaddress: メールアドレス
AccountID: アカウントID
CurrentPassword: パスワード
NewPassword: 新しいパスワード
ConfirmPassword: 新しいパスワード(確認)

Owl: Owl
Home: ホーム
Help: ヘルプ
AdminTool: システム管理
Settings: 設定
Logout: ログアウト

ForgetPassword: パスワードを忘れた?
Usage: 使用方法

SendReminderMail: リマインダメール送信

NOTE: NOTE

Account: アカウント
Password: パスワード
Email: メール
Profile: プロフィール

Update: 更新する
Edit: 編集する
ChangeAvatar: アバターの変更
UploadPhotos: 写真をアップロードする
EditProfile: プロフィールの編集
EditComment: コメントの編集

ChoiceAsAvatar: アバターにする
FirePhoto: 写真を削除する

Browse: 参照
Upload: アップロード

FamilyName: 姓
GivenName: 名

Close: 閉じる

AdministratorsToolbox: 管理ツール
MaintUser: ユーザ管理
ImportUser: ユーザインポート
MaintClient: クライアント管理

AddNewFace: 新規ユーザ追加
EditUser: 編集
KillUser: 削除

Warning: 警告!
Danger: 危険!
Important: 重要!

AddNewClient: 新規クライアント追加
ClientID: クライアントID
ClientName: クライアント名
ClientSecret: クライアント秘密キー
EditClient: クライアント編集
Fire: 削除
