OwlSystem: Owl認証システム
ThisIsOwl: Owl認証システムです.
LoginFromHere: こちらからログインしてください.

Emailaddress: メールアドレス
AccountID: アカウントID
CurrentPassword: 現在のパスワード
NewPassword: 新しいパスワード
ConfirmPassword: パスワード(確認)
ConfirmNewPassword: 新しいパスワード(確認)

Owl: Owl
Home: ホーム
Help: ヘルプ
AdminTool: システム管理
Settings: 設定
Logout: ログアウト

ForgetPassword: パスワードを忘れた?
IfYouLostPassword: パスワードを忘れた場合には,リマインダメールを使ってパスワードをリセットしてください.
ReceiveReminderMail: リマインダメールに記載しているアカウントで一時的にログインできるようになります.
Usage: 使用方法
DescrptForUsage: (No description)

SendReminderMail: リマインダメール送信
FailSentReminderMail: リマインダメールの送信に失敗しました

SendVerifyMail: 認証確認メール送信
FailSentVerifyMail: 確認メールの送信に失敗しました

NOTE: NOTE

Account: アカウント
Password: パスワード
Email: メール
Verkey: 確認キー
Verstatus: 確認ステータス
Profile: プロフィール

Update: 更新する
Edit: 編集する
EditProfile: プロフィールの編集
EditComment: コメントの編集

UploadFilePath: ファイルパス
Browse: 参照
Upload: アップロード

FamilyName: 姓
GivenName: 名
Role: ロール

Add: 追加
Close: 閉じる

AdministratorsToolbox: 管理ツール
MaintUser: ユーザ管理
ImportUser: ユーザインポート
MaintClient: クライアント管理

AddNewFace: 新規ユーザ追加
CreateUser: 作成
CreateNewFace: 新規ユーザを作成しました.
FailToCreateUser: ユーザの作成に失敗しました.
EditUser: 編集
KillUser: 削除
UserKilled: ユーザを削除しました.
NoteToKillUser: ユーザの削除は十分確認して行ってください.削除したアカウントを元に戻すことは出来ません.

Warning: 警告!
Danger: 危険!
Important: 重要!

AddNewClient: 新規クライアント追加
ClientID: クライアントID
ClientName: クライアント名
ClientSecret: クライアント秘密キー
EditClient: クライアント編集
Fire: 削除
YouUnauthorizedClient: 正規のクライアントではありません.

PasswordUpdated: パスワードを変更しました.
PasswordsUnmatch: 新しいパスワードが異なります.
FailToUpdatePassword: パスワードの変更に失敗しました.
InvalidCurrentPassword: 現在のパスワードが間違っています.

Verify: 認証する
VerifyKey: 認証キー
VerifyYourEmail: メールアドレスを認証してください.
YourVerifyingEmail: メールアドレス
NotSetAnyEmail: メールアドレスが登録されていません.
SuccessVerifyEmail: メールアドレスの確認に成功しました.
FailVerifyEmail: メールアドレスの確認に失敗しました.
SentVerifyMail: 確認メールを送信しました.

UpdateProfile: プロフィールを更新しました.
FailUpdateProfile: プロフィールの更新に失敗しました.

NoEmailAddress: メールアドレス未設定
Fullname: 氏名

UpdateEmailaddress: メールアドレスを更新しました.
FailToUpdateEmail: メールアドレスの更新に失敗しました.

AboutCSVFormat: 文字コードはUTF-8で書かれていることと,先頭にヘッダ行が必要です.フィールドの書式を以下にしめします.
AboutAccountIdColumn: ユーザアカウントID
AboutPasswordColumn: デフォルトパスワード
AboutEmailColumn: ユーザのメールアドレス
AboutFamilyNameColumn: ユーザの姓
AboutGivenNameColumn: ユーザの名前

SuccessImportUsers: ユーザのインポートに成功しました.
FailToImportUsers: ユーザのインポートに失敗しました.

ThisMailaddressIs: このメールアドレスは現在
Post4ThisMailaddressIs: です.

UnverifiedEmailaddress: メールアドレスがまだ有効ではありません.
TheAccountPasswordInvalid: そのアカウントとパスワードは有効ではありません.

NoteToChangeOthersPassword: ユーザのパスワード変更は注意して行ってください.
NoteToChangeOthersEmail: ユーザのメールアドレス変更は注意して行ってください.

ConfigUserSetting: ユーザ設定
DescriptForConfigSetting: 現在のバージョンでは設定可能な項目はありません.
