Emailaddress: メールアドレス
AccountID: アカウントID
CurrentPassword: パスワード
NewPassword: 新しいパスワード
ConfirmPassword: 新しいパスワード(確認)

Owl: Owl
Home: ホーム
Help: ヘルプ
AdminTool: システム管理
Settings: 設定
Logout: ログアウト

ForgetPassword: パスワードを忘れた?
Usage: 使用方法

SendReminderMail: リマインダメール送信
FailSentReminderMail: リマインダメールの送信に失敗しました

SendVerifyMail: 認証確認メール送信
FailSentVerifyMail: 確認メールの送信に失敗しました

NOTE: NOTE

Account: アカウント
Password: パスワード
Email: メール
Verkey: 確認キー
Verstatus: 確認ステータス
Profile: プロフィール

Update: 更新する
Edit: 編集する
EditProfile: プロフィールの編集
EditComment: コメントの編集

UploadFilePath: ファイルパス
Browse: 参照
Upload: アップロード

FamilyName: 姓
GivenName: 名

Close: 閉じる

AdministratorsToolbox: 管理ツール
MaintUser: ユーザ管理
ImportUser: ユーザインポート
MaintClient: クライアント管理

AddNewFace: 新規ユーザ追加
EditUser: 編集
KillUser: 削除

Warning: 警告!
Danger: 危険!
Important: 重要!

AddNewClient: 新規クライアント追加
ClientID: クライアントID
ClientName: クライアント名
ClientSecret: クライアント秘密キー
EditClient: クライアント編集
Fire: 削除

PasswordUpdated: パスワードを変更しました.
FailToUpdatePassword: パスワードの変更に失敗しました.

Verify: 認証する
VerifyKey: 認証キー
VerifyYourEmail: メールアドレスを認証してください.
YourVerifyingEmail: メールアドレス
NotSetAnyEmail: メールアドレスが登録されていません.
SuccessVerifyEmail: メールアドレスの確認に成功しました.
FailVerifyEmail: メールアドレスの確認に失敗しました.
SentVerifyMail: 確認メールを送信しました.

UpdateProfile: プロフィールを更新しました.
FailUpdateProfile: プロフィールの更新に失敗しました.

NoEmailAddress: メールアドレス未設定
Fullname: 氏名

UpdateEmailaddress: メールアドレスを更新しました.
FailToUpdateEmail: メールアドレスの更新に失敗しました.
