Default: &defaults
  user: cutsea110
  password: cutsea110
  host: localhost
  port: 5432
  database: owl
  poolsize: 10

Development:
  database: owl_devel
  <<: *defaults

Testing:
  database: owl_test
  <<: *defaults

Staging:
  database: owl_staging
  poolsize: 100
  <<: *defaults

Production:
  database: owl_production
  poolsize: 100
  <<: *defaults
