Default: &defaults
  host: "*4" # any IPv4 host
  port: 3002
  approot: "http://localhost:3002"
  copyright: Insert copyright statement here
  #analytics: UA-YOURCODE

Development:
  port: 3002
  approot: "http://localhost:3002"
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  approot: "https://bisocie2.basement.timedia.co.jp/_owl"
  <<: *defaults

Production:
  #approot: "https://bisocie2.basement.timedia.co.jp/_owl"
  approot: "https://bisocie.seitoku.ac.jp/_owl"
  <<: *defaults
